name: lipa_na_mpesa_online
description: This is a dart mpesa daraja api from safaricom sandbox online payment. Written in pure dart for(ios, android, web and in plain native dart) and works.
version: 1.0.0
author: kahdichienjah

homepage: https://github.com/kahdichienja/lipanampesa
repository: https://github.com/kahdichienja/lipanampesa
issue_tracker: https://github.com/kahdichienja/lipanampesa/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


